### ISSUE TITLE
Physics

### ISSUE THREAD

**Issue by tomaspietravallo** [tomaspietravallo/sparkar-volts#6]
## Update:
The current plan is to add a high performance physics engine within Volts itself. Complete with gravity, collisions, and more.

```ts
Object3D.usePhysics()
```

`usePhysics` should take care of collision detection and response all on it's own. While being moderately fast.

### The objective:
- [x] Add accurate real-world physics. Linear, accelerated, and parabolic trajectories
- [ ] 100+ objects on scene at any given time 

## Tasks:

- [x] Matrix class
- [x] OBB Collision detection
- [ ] #18
- [ ] Optimization of OBB collisions 

---

<details><summary>Read the old issue by clicking on the arrow. Note that this is no longer the objective</summary>
Add a method that binds the current code base to other libraries such as Oimo.js, Cannon.js, or others.

Ideally *physics* would be its own separate script that can be loaded & bound as needed, in order to not have huge amounts of unused code; which adds to size and initial load times (I don't know the extent to which the latter is a significant issue)

This issue will probably stay `on hold` until: 
 - ~The BoundingBox signal works properly~
 - ~VOLTS itself is more robust~
 - ~[The TransformSignal bug](https://docs.google.com/document/d/1Dj22O5SLGfMbTU5-oqBzlU78J9V1nMUVGo9gEGxziMA/edit?usp=sharing) is addressed~
</details>

**Comment by tomaspietravallo** [comment]
> The BoundingBox signal works properly

It doesn't yet... but with [onNextTick](b7a015f23075fad8af26b15ca60d53a37fccd9f0) and the [Snapshot](#7) the values can be fetched

**Comment by tomaspietravallo** [comment]
- [Added to the roadmap for v5.0.0](48c5834bb3537c5a3c88089a4a6feb1223bfb119) 48c5834bb3537c5a3c88089a4a6feb1223bfb119
- [Added usePhysics on beta](https://github.com/tomaspietravallo/sparkar-volts/commit/689b7672f5fbc5d9896e096cd147b89e779cf75a) https://github.com/tomaspietravallo/sparkar-volts/commit/689b7672f5fbc5d9896e096cd147b89e779cf75a

**Comment by tomaspietravallo** [comment]
An impulse/ Matrix based solver would be a nice addition. Help needed.

- A matrix class with
  - [x] inverse
  - [x] transpose
  - [x] multiply-vector-by-matrix

would be of huge help

> Update: all have been added, along with their tests

**Comment by tomaspietravallo** [comment]
References:
- https://en.wikipedia.org/wiki/Gaussian_elimination
- https://en.wikipedia.org/wiki/Invertible_matrix
- https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/matrix-inverse

**Comment by tomaspietravallo** [comment]
The size (SLOC) of the physics solver alone is making me consider splitting up volts into multiple files that later get packed. Downside would be modifying things across 'compiled' versions would be hard, making modifying things inside of Spark difficult

> The SLOC size of the Verlet solver is quite small, but impulse, AABB, collision detection, etc all will be huge. Will need to consider how to structure it
